config-version = 2
# -------------------------------------------
#  AeroSpace CONFIG
#  Place this file in: ~/.aerospace.toml
# -------------------------------------------
start-at-login = true
# -------------------------------------------
#  NORMALIZATION & LAYOUTS
# -------------------------------------------
enable-normalization-flatten-containers = true

enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'


automatically-unhide-macos-hidden-apps = false

persistent-workspaces = ["1", "2", "3","4"]

on-mode-changed = []



# -------------------------------------------
#  KEY MAPPING
# -------------------------------------------

[key-mapping]
preset = 'qwerty'


# -------------------------------------------
#  GAPS
# -------------------------------------------

[gaps]
inner.horizontal = 8
inner.vertical   = 8
outer.left       = 8
outer.bottom     = 8
outer.top        = 8
outer.right      = 8


# -------------------------------------------
#  MAIN MODE KEYBINDINGS
# -------------------------------------------

[mode.main.binding]
cmd-h = 'mode main'  # disable macOS hide

# Layouts
alt-shift-slash = 'layout tiles horizontal vertical'
alt-shift-comma = 'layout accordion horizontal vertical'
alt-shift-f = ['layout floating tiling', 'mode main']
alt-shift-m = ['fullscreen', 'mode main']
# Movement & Focus
alt-shift-h = 'focus left'
alt-shift-j = 'focus down'
alt-shift-k = 'focus up'
alt-shift-l = 'focus right'

# Move window within the workspace (cmd-shift + hjkl)
cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'



# Resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
# Reset all windows in the workspace to equal sizes
alt-shift-0 = 'balance-sizes'

# Workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-semicolon = 'mode service'



# -------------------------------------------
#  SERVICE MODE
# -------------------------------------------

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']


# -------------------------------------------
#  APPLICATION ROUTING / AUTO-WORKSPACES
# -------------------------------------------


